# Generated by Django 3.1.2 on 2020-10-29 12:30

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prop', models.CharField(max_length=100, unique=True)),
                ('value', models.CharField(max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Entity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('quantity_unit', models.CharField(blank=True, max_length=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='EntityType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='ExpenseCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='PaymentModeCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('last_modified_by', models.CharField(max_length=50, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Settlement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('date', models.DateField(unique=True)),
                ('opening_cash', models.PositiveIntegerField()),
                ('closing_cash', models.PositiveIntegerField()),
                ('cash_expense', models.PositiveIntegerField(default=0)),
                ('expense', models.PositiveIntegerField(default=0)),
                ('is_closed', models.BooleanField(default=False)),
                ('closed_by', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('last_modified_by', models.CharField(max_length=50, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-date'],
                'get_latest_by': '-date',
            },
        ),
        migrations.CreateModel(
            name='SaleSummary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('software_data', models.JSONField(null=True)),
                ('manager_data', models.JSONField(null=True)),
                ('software_sale', models.PositiveIntegerField()),
                ('manager_sale', models.PositiveIntegerField()),
                ('software_discount', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('last_modified_by', models.CharField(max_length=50, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('settlement', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.settlement')),
            ],
            options={
                'ordering': ['-date'],
                'get_latest_by': '-date',
            },
        ),
        migrations.CreateModel(
            name='PaymentMode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('display_name', models.CharField(max_length=50, unique=True)),
                ('display_in', models.CharField(choices=[('MANAGER', 'SaleSummary: ManagerColumn'), ('SOFTWARE', 'SaleSummary: SoftwareColumn'), ('BOTH', 'SaleSummary: Manager & Software Columns')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='api.paymentmodecategory')),
            ],
        ),
        migrations.CreateModel(
            name='EntryCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('entity_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.entitytype')),
                ('expense_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='api.expensecategory')),
            ],
        ),
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('DE', 'DEBIT'), ('CR', 'CREDIT')], default='DE', max_length=2)),
                ('date', models.DateField()),
                ('mode', models.CharField(choices=[('CA', 'CASH'), ('AC', 'ACCOUNT'), ('TR', 'TREASURE')], default='CA', max_length=2)),
                ('comment', models.CharField(blank=True, max_length=100, null=True)),
                ('amount', models.PositiveIntegerField()),
                ('quantity', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('quantity_unit', models.CharField(blank=True, max_length=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('created_by', models.CharField(max_length=50, null=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.entrycategory')),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.entity')),
                ('settlement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.settlement')),
            ],
            options={
                'ordering': ['-date', 'type'],
            },
        ),
        migrations.AddField(
            model_name='entity',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.expensecategory'),
        ),
        migrations.AddField(
            model_name='entity',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.entitytype'),
        ),
        migrations.AlterUniqueTogether(
            name='entity',
            unique_together={('name', 'category')},
        ),
    ]
