# Generated by Django 3.0.4 on 2020-03-15 10:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='date',
            field=models.DateField(default=django.utils.timezone.now, unique=True),
            preserve_default=False,
        ),
    ]
