# Generated by Django 3.0.4 on 2020-03-17 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_entry_amout'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentmode',
            name='display_name',
            field=models.CharField(default='', max_length=50, unique=True),
            preserve_default=False,
        ),
    ]
