# Generated by Django 3.0.4 on 2020-03-19 16:34

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_paymentmode_display_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesummary',
            name='manager_data',
            field=jsonfield.fields.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='salesummary',
            name='software_data',
            field=jsonfield.fields.JSONField(null=True),
        ),
    ]
