# Generated by Django 3.0.4 on 2020-03-22 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20200319_2204'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entry',
            old_name='amout',
            new_name='amount',
        ),
    ]
