# Generated by Django 3.0.4 on 2020-03-27 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20200326_1940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settlement',
            name='closed_by',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
