# Generated by Django 3.0.4 on 2020-03-28 12:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20200327_2335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesummary',
            name='settlement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Settlement', unique=True),
        ),
    ]
