# Generated by Django 3.0.4 on 2020-04-01 10:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_auto_20200328_1815'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entity',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.ExpenseCategory'),
        ),
    ]
