# Generated by Django 3.0.4 on 2020-04-01 15:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_auto_20200328_1815'),
    ]

    operations = [
        migrations.AddField(
            model_name='entrycategory',
            name='expense_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='api.ExpenseCategory'),
        ),
        migrations.AlterField(
            model_name='entity',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.ExpenseCategory'),
        ),
        migrations.AlterField(
            model_name='entity',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='salesummary',
            name='settlement',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.Settlement'),
        ),
        migrations.AlterUniqueTogether(
            name='entity',
            unique_together={('name', 'category')},
        ),
    ]
